const SearchActionType = {
  FETCH_SEARCH_MOVIE_START: "FETCH_SEARCH_MOVIE_START",
  FETCH_SEARCH_MOVIE_SUCCESS: "FETCH_SEARCH_MOVIE_SUCCESS",
  FETCH_SEARCH_MOVIE_FAILURE: "FETCH_SEARCH_MOVIE_FAILURE",
  SEARCH_INPUT: "SEARCH_INPUT",
  CLEAR_SEARCH_ENTRY: "CLEAR_SEARCH_ENTRY",
  CLEAR_SEARCH_COLLECTIONS: "CLEAR_SEARCH_COLLECTIONS",
  EXPAND_SEARCH_INPUT: "EXPAND_SEARCH_INPUT",
};
export default SearchActionType;
