try{;(function(){var aC=window._vwo_code;if(aC){window._vwo_j_e=window._vwo_j_e||0;if(window._vwo_j_e==1){window._vwo_mt="dupCode";clearTimeout(window._vwo_settings_timer);if(window.VWO&&window.VWO._&&window.VWO._.bIE){window._vwo_code.finish()}return}if(window._vwo_j_e==-1){window._vwo_j_e=1}}window._vwo_mt="live";try{window._vwo_tm="";var getMode=function(e){var n;if(window.name.indexOf(e)>-1){n=window.name}else{n=window.location.search.match("_vwo_m=([^&]*)");n=n&&n[1]}return n&&JSON.parse(decodeURIComponent(n))};if(window.name.indexOf("_vis_heatmap")>-1||window.name.indexOf("_vis_editor")>-1||getMode("_vwo_cc")||window.name.indexOf("_vis_preview")>-1){window._vwo_mt=window.name}else if(window._vwo_tm.length){window._vwo_mt=window._vwo_tm}else if(location.href.indexOf("_vis_opt_preview_combination")!==-1&&location.href.indexOf("_vis_test_id")!==-1){window._vwo_mt="sharedPreview"}if(window._vwo_mt!=="live"){if(!getMode("_vwo_cc")){_vwo_code.load('https://dev.visualwebsiteoptimizer.com/j.php?mode=' + encodeURIComponent(window._vwo_mt) + '&a=27087&f=1&u=' + encodeURIComponent(window._vis_opt_url||document.URL));}else{(function(){window._vwo_code&&window._vwo_code.finish();_vwo_ccc={u:"/j.php?a=27087&u=https%3A%2F%2Fwww.oreilly.com%2F&f=1&r=0.7675828481832119"};var s=document.createElement("script");s.src="https://app.vwo.com/visitor-behavior-analysis/dist/codechecker/cc.min.js?r="+Math.random();document.head.appendChild(s)})()}}}catch(e){var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?s=mode_det&e="+encodeURIComponent(e&&e.stack&&e.stack.substring(0,1e3));aC&&window._vwo_code.finish()}})();if(window._vwo_mt==='live'){;window.VWO = window.VWO || []; window.VWO.push(['modifyClickPauseTime', { time: 0 }]);_vwo_code.sT=_vwo_code.finished();(function(c,a,e,d,b,z){function f(a,b,d){e.cookie=a+"="+b+"; expires="+new Date(864e5*d+ +new Date).toGMTString()+"; domain="+c+"; path=/"}-1==e.cookie.indexOf("_vis_opt_out")&&-1==d.location.href.indexOf("vwo_opt_out=1")&&(a=e.cookie.replace(/(?:(?:^|.*;\s*)_vwo_uuid_v2\s*=\s*([^;]*).*$)|^.*$/,"$1")||a,a=a.split("|"),b=new Image,c=d.location.hostname.replace(/^www\./,"")||c,b.src="https://dev.visualwebsiteoptimizer.com/v.gif?cd="+(window._vis_opt_cookieDays||0)+"&a=27087&d="+encodeURIComponent(c)+"&u="+a[0]+"&h="+a[1]+"&t="+z+"&r="+Math.random(),d.vwo_iehack_queue=[b],f("_vwo_uuid_v2",a.join("|"),366))})("oreilly.com","D214A5EDDE8DC6DED93C26AAE4D38D09F|63cd5ff6a52c48d92fca83810b8bc8ad",document,window,0,_vwo_code.sT);var _vwo_acc_id=27087;
clearTimeout(_vwo_settings_timer);_vwo_exp_ids=[],_vwo_exp={};window.VWO=window.VWO||[];
window.VWO.data={"ts":1650715425,"noSS":false};window.VWO.featureInfo={};_vwo_exp_ids.push('197');_vwo_exp['197']={"version":4,"ep":1650401023000,"clickmap":0,"globalCode":{},"isEventMigrated":false,"type":"VISUAL_AB","status":"RUNNING","pc_traffic":100,"name":"Homepage Radar Prehead CTA - More Goals","manual":false,"urlRegex":"^https\\:\\\/\\\/oreilly\\.com\\\/?(?:[\\?#].*)?$","exclude_url":"","multiple_domains":0,"segment_code":"true","ss":null,"ibe":1,"sections":{"1":{"path":"","variations":{"1":"[]","2":"[{\"js\":\"<style>.va{display:none!important}.vb{display:block!important}<\\\/style>\",\"xpath\":\"HEAD\"}]"},"segment":{"1":1,"2":1},"segmentObj":[]}},"varSegAllowed":false,"combs":{"1":0.5,"2":0.5},"comb_n":{"1":"Control","2":"Variation-1"},"goals":{"1":{"url":"#requestDemo1-cta, #requestDemo1-cta-b","type":"CLICK_ELEMENT"},"3":{"url":"#radar-preheadCta, #radar-image, #radar-cta","type":"CLICK_ELEMENT"},"4":{"urlRegex":"^https\\:\\\/\\\/oreilly\\.com\\\/online\\-learning\\\/teams\\.html\\\/?(?:[\\?#].*)?$","excludeUrl":"","type":"CUSTOM_GOAL"},"201":{"urlRegex":"^https\\:\\\/\\\/oreilly\\.com\\\/online\\-learning\\\/radar\\-event\\-cloud\\-2022\\.html\\\/?(?:[\\?#].*)?$|^https\\:\\\/\\\/oreilly\\.com\\\/online\\-learning\\\/radar\\-event\\-cloud\\-apac\\-2022\\.html\\\/?(?:[\\?#].*)?$","excludeUrl":"","type":"CUSTOM_GOAL"}},"pgre":true,"ps":true};var vwoCode = window._vwo_code; if(vwoCode.filterConfig && vwoCode.filterConfig.filterTime==='balanced'){ vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay() };var _vwo_style=document.getElementById('_vis_opt_path_hides'),_vwo_css= window._vwo_el_style || '{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;} :root {--vwo-el-opacity:0 !important;--vwo-el-filter:alpha(opacity=0) !important;--vwo-el-bg:none !important;}';
if(_vwo_style){_vwo_style.parentNode.removeChild(_vwo_style);}(function(){var VWOOmniTemp={};window.VWOOmni=window.VWOOmni||{};window.VWOOmni={...window.VWOOmni,...VWOOmniTemp};;})();    (function(){window.VWO=window.VWO||[];var pollInterval=100;
        var _vis_data={};
        var intervalObj={};
        var analyticsTimerObj={};
        var experimentListObj={};window.VWO.push(["onVariationApplied",function(data){if(!data){return}var expId=data[1],variationId=data[2];if(expId&&variationId&&["VISUAL_AB","VISUAL","SPLIT_URL"].indexOf(window._vwo_exp[expId].type)>-1){}}])})();
            "function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(e,t){"use strict";if(null==e)throw new TypeError("Cannot convert undefined or null to object");for(var n=Object(e),r=1;r<arguments.length;r++){var o=arguments[r];if(null!=o)for(var c in o)Object.prototype.hasOwnProperty.call(o,c)&&(n[c]=o[c])}return n},writable:!0,configurable:!0});
    if(_vwo_exp[197]) Object.assign(_vwo_exp[197],{"GTM":1});window.VWO.data.vi = window.VWO.data.vi || {"de":"Other","dt":"desktop","br":"Chrome","os":"Windows"};
window.VWO.push(['enableSPA']);
VWO.load_co=function(a){var b=document.createElement('script');b.src=a;b.crossOrigin='anonymous';b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};document.getElementsByTagName('head')[0].appendChild(b);}
var _vwo_cookieDomain = 'oreilly.com', _vwo_uuid = 'D214A5EDDE8DC6DED93C26AAE4D38D09F';window.VWO=window.VWO||[];VWO._=VWO._||{};var _vis_opt_file = _vwo_code.use_existing_jquery() ? '7.0/vanj-3a8c03cc83fd9c554b5af6e1cc1ffa80.js' : '7.0/va-3a8c03cc83fd9c554b5af6e1cc1ffa80.js',_vwo_library_timer = setTimeout(function () {var vwoCode = _vwo_code; vwoCode.removeLoaderAndOverlay && vwoCode.removeLoaderAndOverlay(); vwoCode.finish()},vwoCode.library_tolerance()),_vis_opt_lib = (typeof _vis_opt_lib=='undefined')?'https://dev.visualwebsiteoptimizer.com/'+_vis_opt_file:_vis_opt_lib;VWO.load_co(_vis_opt_lib);window.VWO.data.as = "r1.visualwebsiteoptimizer.com";;window.VWO=window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};; 
window.VWO = window.VWO || [];
window.VWO.data = window.VWO.data || {};
VWO.data.content={"fns":{"list":{"vn":1,"args":{"1":{}}}}};;window.VWO = window.VWO||[];window.VWO._=window.VWO._||{};VWO._.ac=VWO._.ac||{};VWO._.ac.dNdOfst=1000;}}catch(e){_vwo_code.finish(); _vwo_code.removeLoaderAndOverlay && _vwo_code.removeLoaderAndOverlay(); var b=new Image;b.src="https://dev.visualwebsiteoptimizer.com/e.gif?a=27087&s=j.php&e="+encodeURIComponent(e && e.message && e.message.substring(0,1000))}